PADDLE_WIDTH = 100;
BRICKS_GRID_WIDTH = 14;
BRICKS_GRID_HEIGHT = 8; // May get funky if this isn't divisible by 4
YELLOW_BRICK = 1;
ORANGE_BRICK = 2;
BLUE_BRICK = 3;
GREEN_BRICK = 5;
MAX_POSSIBLE_SCORE = (YELLOW_BRICK+ORANGE_BRICK+BLUE_BRICK+GREEN_BRICK)*((BRICKS_GRID_HEIGHT/4)*BRICKS_GRID_WIDTH);
